Repository CERP/education, pull requests merged in 2021-07, with the labels that each got.

#382 bugfixes/mudassar/v1.0.0 (#381)
  web/CHANGELOG.md
  web/src/components/Printable/Student/cardlist.tsx
  web/src/constants/form-defaults.ts
  web/src/pages/auth/login/staff.tsx
  web/src/pages/family/single/payments.tsx
  web/src/pages/onboarding/class/index.tsx
  web/src/pages/onboarding/completion/index.tsx
  web/src/pages/onboarding/index.tsx
  web/src/pages/onboarding/staff/index.tsx
  web/src/pages/onboarding/student/add.tsx
  web/src/pages/onboarding/student/index.tsx
  web/src/pages/students/fee-payments/payments.tsx
  web/src/pages/students/list.tsx
  web/src/utils/calculateDuesAsync.ts
  web/src/utils/checkStudentDues.ts
Labels: bug, enhancement, good first issue

#385 hot-fixes-for-v1.0.2
  web/CHANGELOG.md
  web/package-lock.json
  web/package.json
  web/src/components/input/search.tsx
  web/src/hooks/useFamily.ts
  web/src/hooks/useGeneratePayments.ts
  web/src/modules/Analytics/DailyStats/index.tsx
  web/src/modules/Analytics/Fees/index.tsx
  web/src/modules/Class/Single/ClassFeeMenu/index.tsx
  web/src/modules/Student/ManageFees.tsx
  web/src/modules/Student/Single/Fees/StudentLedgerPage.tsx
  web/src/modules/TIP/DetailedAnalysis/ClassView/index.tsx
  web/src/modules/TIP/DetailedAnalysis/GroupView/index.tsx
  web/src/pages/class/create.tsx
  web/src/pages/class/list.tsx
  web/src/pages/family/list.tsx
  web/src/pages/family/single/index.tsx
  web/src/pages/family/single/payments.tsx
  web/src/pages/home/settings.tsx
  web/src/pages/home/statistics.tsx
  web/src/pages/onboarding/completion/index.tsx
  web/src/pages/onboarding/student/index.tsx
  web/src/pages/school/diary/index.tsx
  web/src/pages/school/fees/index.tsx
  web/src/pages/school/fees/print-voucher/index.tsx
  web/src/pages/school/fees/print-voucher/preview.tsx
  web/src/pages/school/fees/reset/index.tsx
  web/src/pages/school/fees/settings/additional-fee/index.tsx
  web/src/pages/school/fees/settings/additional-fee/single-class.tsx
  web/src/pages/school/fees/settings/additional-fee/single-student.tsx
  web/src/pages/school/fees/settings/default.tsx
  web/src/pages/school/fees/settings/scholarship.tsx
  web/src/pages/sms/index.tsx
  web/src/pages/staff/attendance/index.tsx
  web/src/pages/staff/index.tsx
  web/src/pages/students/add/excel-import.tsx
  web/src/pages/students/add/index.tsx
  web/src/pages/students/attendance/index.tsx
  web/src/pages/students/attendance/sms-modal-content-wrapper.tsx
  web/src/pages/students/fee-payments/payments.tsx
  web/src/pages/students/index.tsx
  web/src/pages/students/list.tsx
  web/src/utils/calculateDuesAsync.ts
  web/src/utils/checkStudentDues.ts
  web/src/utils/index.ts
Labels: bug, enhancement, good first issue

#388 hot-fixes-for-v1.0.3
  web/CHANGELOG.md
  web/src/modules/Class/List/index.js
  web/src/pages/home/settings.tsx
  web/src/pages/school/diary/index.tsx
  web/src/pages/school/settings/index.tsx
  web/src/pages/students/add/index.tsx
  web/src/utils/index.ts
Labels: bug

#384 Promote students
  web/src/pages/exams/promote-students/index.tsx
  web/src/routing/index.tsx
Labels: enhancement

#394 mischool-web@v1.1.0
  web/CHANGELOG.md
  web/src/actions/index.ts
  web/src/components/Printable/Student/StudentAttendancePrint.tsx
  web/src/components/attendance/index.tsx
  web/src/pages/auth/login/staff.tsx
  web/src/pages/auth/mis-activation/index.tsx
  web/src/pages/class/create.tsx
  web/src/pages/exams/promote-students/index.tsx
  web/src/pages/expense/salary/member/index.tsx
  web/src/pages/family/list.tsx
  web/src/pages/family/single/index.tsx
  web/src/pages/school/fees/voucher-settings/index.tsx
  web/src/pages/school/settings/index.tsx
  web/src/pages/students/attendance/single/index.tsx
  web/src/pages/students/index.tsx
  web/src/pages/students/list.tsx
  web/src/routing/index.tsx
  web/src/utils/getSectionsFromClasses.ts
  web/src/utils/index.ts
Labels: bug, enhancement
